# Generated by Django 5.2.10 on 2026-01-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.classgroup')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
            options={
                'verbose_name': 'Session access',
                'verbose_name_plural': 'Session access',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='allowed_classes',
            field=models.ManyToManyField(related_name='sessions', through='core.SessionClass', to='core.classgroup'),
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('constraints', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.session')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('pin_hash', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.classgroup')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('finish_reason', models.CharField(blank=True, choices=[('completed', 'Completed'), ('timeout', 'Timeout'), ('manual', 'Manual close')], max_length=16, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='core.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='core.student')),
            ],
            options={
                'verbose_name': 'Student session',
                'verbose_name_plural': 'Student sessions',
            },
        ),
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('solved', 'Solved'), ('locked', 'Locked')], default='not_started', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_total', models.PositiveIntegerField(default=0)),
                ('attempts_failed', models.PositiveIntegerField(default=0)),
                ('hint1_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('hint2_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('hint1_text', models.TextField(blank=True)),
                ('hint2_text', models.TextField(blank=True)),
                ('locked_after_solve', models.BooleanField(default=True)),
                ('student_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='core.studentsession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.sessiontask')),
            ],
            options={
                'verbose_name': 'Task progress',
                'verbose_name_plural': 'Task progress',
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('copy', 'Copy'), ('paste', 'Paste'), ('tab_hidden', 'Tab hidden'), ('tab_visible', 'Tab visible'), ('focus_lost', 'Focus lost'), ('focus_gained', 'Focus gained'), ('open_task', 'Open task'), ('submit', 'Submit')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='core.studenttaskprogress')),
            ],
            options={
                'verbose_name': 'Activity event',
                'verbose_name_plural': 'Activity events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('total_pastes', models.PositiveIntegerField(default=0)),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('focus_lost_count', models.PositiveIntegerField(default=0)),
                ('active_time_seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_agg', to='core.studenttaskprogress')),
            ],
            options={
                'verbose_name': 'Activity aggregate',
                'verbose_name_plural': 'Activity aggregates',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('code', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong answer'), ('runtime_error', 'Runtime error'), ('compile_error', 'Compile error')], max_length=16)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('external_run_id', models.CharField(blank=True, max_length=120)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.studenttaskprogress')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('stdin', models.TextField()),
                ('expected_stdout', models.TextField()),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='core.sessiontask')),
            ],
            options={
                'verbose_name': 'Test case',
                'verbose_name_plural': 'Test cases',
                'ordering': ['task', 'ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionclass',
            constraint=models.UniqueConstraint(fields=('session', 'class_group'), name='uniq_session_class'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='core_sessio_status_c9a98f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontask',
            index=models.Index(fields=['session', 'position'], name='core_sessio_session_3c6f1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessiontask',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='uniq_task_position_in_session'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_group', 'full_name'], name='core_studen_class_g_3d996f_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('class_group', 'full_name'), name='uniq_student_in_class'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['session', 'student'], name='core_studen_session_07a9f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentsession',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='uniq_student_session'),
        ),
        migrations.AddIndex(
            model_name='studenttaskprogress',
            index=models.Index(fields=['student_session', 'task'], name='core_studen_student_f4dd40_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttaskprogress',
            index=models.Index(fields=['status'], name='core_studen_status_a192d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='studenttaskprogress',
            constraint=models.UniqueConstraint(fields=('student_session', 'task'), name='uniq_progress_student_task'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['progress', 'occurred_at'], name='core_activi_progres_40c429_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type'], name='core_activi_event_t_e17884_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['progress', 'attempt_no'], name='core_submis_progres_50609e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='core_submis_submitt_cc7493_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('progress', 'attempt_no'), name='uniq_attempt_no_per_progress'),
        ),
        migrations.AddIndex(
            model_name='tasktestcase',
            index=models.Index(fields=['task', 'is_visible'], name='core_taskte_task_id_f0e13f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktestcase',
            constraint=models.UniqueConstraint(fields=('task', 'ordinal'), name='uniq_testcase_ordinal_in_task'),
        ),
    ]
