# Generated by Django 5.1.2 on 2026-01-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='last_code_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='last_submit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
