# Generated by Django 5.1.2 on 2026-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentsession_last_code_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error')], max_length=32),
        ),
    ]
