# Generated by Django 5.1.2 on 2026-01-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studenttaskprogress_last_code_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssistMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('prompt_snapshot', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='core.studenttaskprogress')),
            ],
            options={
                'indexes': [models.Index(fields=['progress', 'level', 'created_at'], name='core_aiassi_progres_8b9e5a_idx')],
            },
        ),
    ]
