# Generated by Django 5.1.2 on 2026-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aiassistmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityaggregate',
            options={},
        ),
        migrations.AddField(
            model_name='activityaggregate',
            name='hint1_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityaggregate',
            name='hint2_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
