# Generated by Django 5.1.2 on 2026-02-25 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activityaggregate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCodeFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('top', 'Top (prepend)'), ('bottom', 'Bottom (append)')], max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_fragments', to='core.sessiontask')),
            ],
            options={
                'verbose_name': 'Task code fragment',
                'verbose_name_plural': 'Task code fragments',
                'indexes': [models.Index(fields=['task', 'position', 'is_active'], name='core_taskco_task_id_e7961d_idx')],
            },
        ),
    ]
