# Generated by Django 5.1.2 on 2026-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityaggregate',
            name='hint3_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenttaskprogress',
            name='hint3_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studenttaskprogress',
            name='hint3_unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenttaskprogress',
            name='hint3_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
