# Generated by Django 5.1.2 on 2026-04-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_activityaggregate_hint3_requests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryMaterialModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_material_modules', to='core.session')),
            ],
            options={
                'verbose_name': 'Theory material module',
                'verbose_name_plural': 'Theory material modules',
                'ordering': ['session', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TheoryMaterialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('block_type', models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('code', 'Code')], max_length=16)),
                ('heading_level', models.CharField(blank=True, choices=[('h1', 'H1'), ('h2', 'H2')], default='', max_length=8)),
                ('content', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.theorymaterialmodule')),
            ],
            options={
                'verbose_name': 'Theory material block',
                'verbose_name_plural': 'Theory material blocks',
                'ordering': ['module', 'ordinal', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='theorymaterialmodule',
            index=models.Index(fields=['session', 'position', 'is_active'], name='core_theory_session_941697_idx'),
        ),
        migrations.AddIndex(
            model_name='theorymaterialblock',
            index=models.Index(fields=['module', 'ordinal'], name='core_theory_module__a49024_idx'),
        ),
        migrations.AddConstraint(
            model_name='theorymaterialblock',
            constraint=models.UniqueConstraint(fields=('module', 'ordinal'), name='uniq_theory_block_ordinal_in_module'),
        ),
    ]
