# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_theorymaterialmodule_theorymaterialblock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheoryQuizModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("topic", models.CharField(blank=True, default="", max_length=255)),
                ("instructions", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_quiz_modules",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theory quiz module",
                "verbose_name_plural": "Theory quiz modules",
                "ordering": ["session", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TheoryQuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordinal", models.PositiveIntegerField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single choice"),
                            ("open_answer", "Open answer"),
                            ("matching", "Matching"),
                        ],
                        max_length=24,
                    ),
                ),
                ("prompt", models.TextField()),
                ("model_answer", models.TextField(blank=True, default="")),
                ("accept_suitable_answer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.theoryquizmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theory quiz question",
                "verbose_name_plural": "Theory quiz questions",
                "ordering": ["module", "ordinal", "id"],
            },
        ),
        migrations.CreateModel(
            name="TheoryQuizChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordinal", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="core.theoryquizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theory quiz choice",
                "verbose_name_plural": "Theory quiz choices",
                "ordering": ["question", "ordinal", "id"],
            },
        ),
        migrations.CreateModel(
            name="TheoryQuizMatchPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordinal", models.PositiveIntegerField()),
                ("left_text", models.TextField()),
                ("right_text", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairs",
                        to="core.theoryquizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theory quiz match pair",
                "verbose_name_plural": "Theory quiz match pairs",
                "ordering": ["question", "ordinal", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentTheoryQuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_no", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("score_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("answers_json", models.JSONField(blank=True, default=dict)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.theoryquizmodule",
                    ),
                ),
                (
                    "student_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theory_quiz_attempts",
                        to="core.studentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student theory quiz attempt",
                "verbose_name_plural": "Student theory quiz attempts",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="theoryquizmodule",
            index=models.Index(fields=["session", "position", "is_active"], name="core_quiz_sess_pos_act_idx"),
        ),
        migrations.AddIndex(
            model_name="theoryquizquestion",
            index=models.Index(fields=["module", "ordinal"], name="core_quiz_question_ord_idx"),
        ),
        migrations.AddIndex(
            model_name="theoryquizchoice",
            index=models.Index(fields=["question", "ordinal"], name="core_quiz_choice_ord_idx"),
        ),
        migrations.AddIndex(
            model_name="theoryquizmatchpair",
            index=models.Index(fields=["question", "ordinal"], name="core_quiz_pair_ord_idx"),
        ),
        migrations.AddIndex(
            model_name="studenttheoryquizattempt",
            index=models.Index(fields=["student_session", "module"], name="core_quiz_attempt_sm_idx"),
        ),
        migrations.AddIndex(
            model_name="studenttheoryquizattempt",
            index=models.Index(fields=["submitted_at"], name="core_quiz_attempt_sub_idx"),
        ),
        migrations.AddConstraint(
            model_name="theoryquizquestion",
            constraint=models.UniqueConstraint(fields=("module", "ordinal"), name="uniq_theory_quiz_question_ordinal"),
        ),
        migrations.AddConstraint(
            model_name="theoryquizchoice",
            constraint=models.UniqueConstraint(fields=("question", "ordinal"), name="uniq_theory_quiz_choice_ordinal"),
        ),
        migrations.AddConstraint(
            model_name="theoryquizmatchpair",
            constraint=models.UniqueConstraint(fields=("question", "ordinal"), name="uniq_theory_quiz_pair_ordinal"),
        ),
        migrations.AddConstraint(
            model_name="studenttheoryquizattempt",
            constraint=models.UniqueConstraint(
                fields=("student_session", "module", "attempt_no"),
                name="uniq_theory_quiz_attempt_no",
            ),
        ),
    ]
