# Generated by Django 5.1.2 on 2026-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sessiontask_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorymaterialblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('code', 'Code'), ('image', 'Image'), ('video', 'Video')], max_length=16),
        ),
    ]
