# Generated by Django 5.2.10 on 2026-07-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teacher_ownership_shared_sessions_and_task_hints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('presentation_json', models.JSONField(blank=True, default=dict)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='core.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_links', to='core.classgroup')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_links', to='core.exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='allowed_classes',
            field=models.ManyToManyField(related_name='exams', through='core.ExamClass', to='core.classgroup'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('open_text', 'Open text'), ('matching', 'Matching'), ('diagram', 'Diagram')], max_length=20)),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('model_answer', models.TextField(blank=True, default='')),
                ('max_score', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.exam')),
            ],
            options={
                'ordering': ['exam', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamMatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('left_text', models.TextField()),
                ('right_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='core.examquestion')),
            ],
            options={
                'ordering': ['question', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, default='')),
                ('matching_answer', models.JSONField(blank=True, default=dict)),
                ('diagram_xml', models.TextField(blank=True, default='')),
                ('diagram_file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('awarded_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('teacher_feedback', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.examquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam', 'status'], name='exam_attempt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'status'], name='student_exam_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='uniq_exam_student_attempt'),
        ),
        migrations.AddConstraint(
            model_name='examclass',
            constraint=models.UniqueConstraint(fields=('exam', 'class_group'), name='uniq_exam_class'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['owner', 'status'], name='exam_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'position'], name='exam_question_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'position'), name='uniq_exam_question_position'),
        ),
        migrations.AddConstraint(
            model_name='exammatchpair',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='uniq_exam_pair_position'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['attempt', 'question'], name='exam_answer_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_exam_attempt_answer'),
        ),
    ]
