# Generated by Django 5.2.16 on 2026-07-22 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_securitythrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='table_answer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='table_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('open_text', 'Open text'), ('matching', 'Matching'), ('diagram', 'Diagram'), ('table', 'Fill table')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExamIntegrityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_hidden', 'Tab hidden'), ('window_blur', 'Window blur'), ('clipboard', 'Clipboard'), ('shortcut', 'Suspicious shortcut'), ('context_menu', 'Context menu'), ('fullscreen_exit', 'Fullscreen exit')], max_length=24)),
                ('client_event_id', models.CharField(max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=120)),
                ('client_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_events', to='core.examattempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attempt', 'created_at'], name='exam_integrity_attempt_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'client_event_id'), name='uniq_exam_integrity_client_event')],
            },
        ),
    ]
