# Generated by Django 5.2.16 on 2026-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_examanswer_table_answer_examquestion_table_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
