# Generated by Django 5.2.16 on 2026-08-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_classgroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerAssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('stopped', 'Stopped')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_assessment_sessions', to='core.teacher')),
                ('reviewer_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_assessment_sessions', to='core.classgroup')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PeerAssessmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_assessment_assignments', to='core.examattempt')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_assessment_assignments', to='core.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.peerassessmentsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeerAssessmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comment', models.TextField(blank=True, default='')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('objective', 'Objective'), ('incorrect', 'Incorrect'), ('insufficient', 'Insufficient reasoning')], default='pending', max_length=16)),
                ('teacher_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.peerassessmentassignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_assessment_reviews', to='core.examquestion')),
            ],
            options={
                'ordering': ['question__position', 'question_id'],
                'indexes': [models.Index(fields=['assignment', 'moderation_status'], name='peer_review_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'question'), name='uniq_peer_review_question')],
            },
        ),
        migrations.AddIndex(
            model_name='peerassessmentsession',
            index=models.Index(fields=['owner', 'status'], name='peer_session_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='peerassessmentassignment',
            index=models.Index(fields=['session', 'reviewer'], name='peer_assign_reviewer_idx'),
        ),
        migrations.AddConstraint(
            model_name='peerassessmentassignment',
            constraint=models.UniqueConstraint(fields=('session', 'reviewer', 'exam_attempt'), name='uniq_peer_reviewer_attempt'),
        ),
    ]
