# Generated by Django 5.2.16 on 2026-08-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_peerassessmentsession_peerassessmentassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('rubric', models.CharField(choices=[('mind_race', 'Mind race')], default='mind_race', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_modules', to='core.session')),
            ],
            options={
                'ordering': ['session', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('running', 'Running'), ('finished', 'Finished')], default='lobby', max_length=16)),
                ('prompt_snapshot', models.JSONField(blank=True, default=list)),
                ('total_prompts', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_rounds', to='core.classgroup')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderated_game_rounds', to='core.teacher')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='core.gamemodule')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_shape', models.CharField(choices=[('square', 'Square'), ('diamond', 'Diamond'), ('triangle', 'Triangle'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon')], max_length=16)),
                ('avatar_color', models.CharField(max_length=7)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('finish_place', models.PositiveIntegerField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_answer_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_participations', to='core.student')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.gameround')),
            ],
            options={
                'ordering': ['finish_place', 'ready_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MindRacePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('sentence', models.TextField()),
                ('missing_text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.gamemodule')),
            ],
            options={
                'ordering': ['module', 'ordinal', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='gamemodule',
            index=models.Index(fields=['session', 'position', 'is_active'], name='game_module_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamemodule',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='uniq_game_module_position'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['module', 'class_group', 'status'], name='game_round_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('module', 'class_group', 'run_number'), name='uniq_game_round_run_number'),
        ),
        migrations.AddIndex(
            model_name='gameparticipant',
            index=models.Index(fields=['round', 'progress'], name='game_participant_progress_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('round', 'student'), name='uniq_game_round_student'),
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('round', 'finish_place'), name='uniq_game_finish_place'),
        ),
        migrations.AddIndex(
            model_name='mindraceprompt',
            index=models.Index(fields=['module', 'ordinal'], name='mind_race_prompt_idx'),
        ),
        migrations.AddConstraint(
            model_name='mindraceprompt',
            constraint=models.UniqueConstraint(fields=('module', 'ordinal'), name='uniq_mind_race_prompt_order'),
        ),
    ]
