# Generated by Django 5.2.16 on 2026-08-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_gamemodule_gameround_gameparticipant_mindraceprompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('stopped', 'Stopped')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='gameround',
            name='revealed_letters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gameround',
            name='strikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='turn_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='turn_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gameround',
            name='turn_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameround',
            name='used_letters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gamemodule',
            name='rubric',
            field=models.CharField(choices=[('mind_race', 'Mind race'), ('wonder_field', 'Wonder field')], default='mind_race', max_length=24),
        ),
        migrations.CreateModel(
            name='GameRoundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('correct', 'Correct letter'), ('wrong', 'Wrong letter'), ('timeout', 'Turn timeout'), ('penalty', 'Teacher penalty'), ('question_complete', 'Question complete'), ('game_won', 'Game won'), ('game_lost', 'Game lost'), ('game_stopped', 'Game stopped')], max_length=24)),
                ('question_index', models.PositiveIntegerField(default=0)),
                ('letter', models.CharField(blank=True, default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_events', to='core.gameparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.gameround')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['round', 'created_at'], name='game_round_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='WonderFieldQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('prompt', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wonder_questions', to='core.gamemodule')),
            ],
            options={
                'ordering': ['module', 'ordinal', 'id'],
                'indexes': [models.Index(fields=['module', 'ordinal'], name='wonder_question_idx')],
                'constraints': [models.UniqueConstraint(fields=('module', 'ordinal'), name='uniq_wonder_question_order')],
            },
        ),
    ]
