# Generated by Django 5.2.16 on 2026-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_gameround_current_question_index_gameround_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroundevent',
            name='event_type',
            field=models.CharField(choices=[('correct', 'Correct letter'), ('wrong', 'Wrong letter'), ('timeout', 'Turn timeout'), ('penalty', 'Teacher penalty'), ('penalty_removed', 'Teacher removed penalty'), ('question_complete', 'Question complete'), ('game_won', 'Game won'), ('game_lost', 'Game lost'), ('game_stopped', 'Game stopped')], max_length=24),
        ),
    ]
