# Generated by Django 5.2.16 on 2026-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_gameroundevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerassessmentsession',
            name='allowed_exams',
            field=models.ManyToManyField(blank=True, related_name='peer_assessment_sessions', to='core.exam'),
        ),
    ]
