# Generated by Django 5.2.16 on 2026-09-09 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_peerassessmentsession_allowed_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodule',
            name='rubric',
            field=models.CharField(choices=[('mind_race', 'Mind race'), ('wonder_field', 'Wonder field'), ('tournament', 'Tournament')], default='mind_race', max_length=24),
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('question_count', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stages', to='core.gamemodule')),
            ],
            options={
                'ordering': ['module', 'ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('prompt', models.TextField()),
                ('answer', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.tournamentstage')),
            ],
            options={
                'ordering': ['stage', 'ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveSmallIntegerField()),
                ('match_number', models.PositiveSmallIntegerField()),
                ('score_one', models.PositiveSmallIntegerField(default=0)),
                ('score_two', models.PositiveSmallIntegerField(default=0)),
                ('current_question_index', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished')], default='pending', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('player_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_one', to='core.gameparticipant')),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_two', to='core.gameparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='core.gameround')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_wins', to='core.gameparticipant')),
            ],
            options={
                'ordering': ['stage_number', 'match_number', 'id'],
                'indexes': [models.Index(fields=['round', 'status'], name='tournament_match_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'stage_number', 'match_number'), name='uniq_tournament_round_match')],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.UniqueConstraint(fields=('module', 'ordinal'), name='uniq_tournament_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='tournamentquestion',
            constraint=models.UniqueConstraint(fields=('stage', 'ordinal'), name='uniq_tournament_question_order'),
        ),
    ]
