# Generated by Django 5.2.16 on 2026-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_gamemodule_rubric_tournamentstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorymaterialblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('text', 'Text'), ('code', 'Code'), ('image', 'Image'), ('video', 'Video'), ('attachment', 'Attachment')], max_length=16),
        ),
    ]
