# Generated by Django 5.2.16 on 2026-09-20 06:50

import django.db.models.deletion
from django.db import migrations, models


def add_primary_class_memberships(apps, schema_editor):
    Student = apps.get_model("core", "Student")
    StudentClassMembership = apps.get_model("core", "StudentClassMembership")
    StudentClassMembership.objects.bulk_create(
        [
            StudentClassMembership(
                student_id=student_id,
                class_group_id=class_group_id,
            )
            for student_id, class_group_id in Student.objects.values_list(
                "id", "class_group_id"
            )
            if class_group_id
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_theorymaterialblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_shared_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_exams', to='core.exam'),
        ),
        migrations.CreateModel(
            name='StudentClassMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_memberships', to='core.classgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='core.student')),
            ],
            options={
                'ordering': ['class_group__name', 'student__full_name'],
            },
        ),
        migrations.RunPython(
            add_primary_class_memberships,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='student',
            name='class_groups',
            field=models.ManyToManyField(related_name='member_students', through='core.StudentClassMembership', to='core.classgroup'),
        ),
        migrations.AddIndex(
            model_name='studentclassmembership',
            index=models.Index(fields=['class_group', 'student'], name='student_class_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentclassmembership',
            constraint=models.UniqueConstraint(fields=('student', 'class_group'), name='uniq_student_class_membership'),
        ),
    ]
