# Generated by Django 5.2.16 on 2026-09-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_student_multiclass_shared_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='last_question_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='last_question_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='last_question_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_question_wins', to='core.gameparticipant'),
        ),
    ]
