# Generated by Django 5.2.16 on 2026-09-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tournamentmatch_last_question_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveSmallIntegerField()),
                ('answer', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('was_current', models.BooleanField(default=True)),
                ('won_question', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='core.tournamentmatch')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_answer_attempts', to='core.gameparticipant')),
            ],
            options={
                'ordering': ['submitted_at', 'id'],
                'indexes': [models.Index(fields=['match', 'question_index'], name='tour_answer_match_q_idx'), models.Index(fields=['participant', 'submitted_at'], name='tour_answer_player_idx')],
            },
        ),
    ]
